version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=vik
    #   - MONGO_INITDB_ROOT_PASSWORD=secret
    env_file:
      - ./env/mongo.env
    # networks:
    #   - goals-net

  backend:
    build: ./backend
      # args: 
      #   - name=value
      # args are the variables inside the dockerfile
    environment:
      - MONGODB_USERNAME=vik
      - MONGODB_PASSWORD=secret
    volumes:
      - logs:/app/logs
      - /app/node_modules
      - ./backend:/app
    ports:
      - 80:80
    depends_on:
      - mongodb
    networks:
      - goals-net
    


  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    # stdin_open: true
    # tty: true 
    # This two are kept to keep the container running on the interactive mode, which it seems have been fixed at the react side itself
    depends_on:
      - backend
    networks:
      - goals-net

volumes:
  data:
  logs: